- import_playbook: setup-server.yml
- hosts: www
  remote_user: root
  vars_files: secret.yml
  tasks:
    - name: Login to registry
      docker_login:
        registry: registry.efrei.yayo.fr
        username: "louisadam"
        password: '{{ vault_registry_password }}'

    - name: Create container
      docker_container:
        name: my_app
        image: registry.efrei.yayo.fr/louisadam/devops-d03/app:{{ version | default('latest') }}
        exposed_ports:
          - '80'
        ports:
          - 80:80