- hosts: www
  remote_user: root
  tasks:
  - name: Update apt
    apt:
      name: python3-pip
      force_apt_get: True
      update_cache: True

  - name: Install Docker
    include_role:
      name: geerlingguy.docker

  - name: Install docker from pip
    pip:
      name: docker

  - name: Install docker from pip
    pip:
      name: docker-compose

