- hosts: all
  remote_user: root
  vars_files:
    - 'vault'

  tasks:
  - name: Update apt
    apt:
      name: python3-pip
      force_apt_get: True
      update_cache: yes

  - name: Install Docker
    include_role:
      name: geerlingguy.docker

  - name: Install docker from pip
    pip:
      name: docker

  - name: Login to registry
    docker_login:
      registry: registry.efrei.yayo.fr
      username: "louisadam"
      password: '{{ vault_registry_password }}'
