- hosts: db
  remote_user: root

  tasks:
  - name: Create container
    docker_container:
      name: redis
      image: redis:latest
      exposed_ports:
        - 6379
      ports:
        - 6379:6379