- hosts: www
  remote_user: root
  tasks:
    - name: write 100 times my name in file
      lineinfile:
        path: "/ex05.txt"
        line: "Louis \n"
        create: "yes"
      with_sequence: start=0 end=100

    - name: destroy test file
      file:
        path: "/test.txt"
        state: absent